version: '3.3'
networks: 
  my-mqtt:
    external: true

services:
    mosquitto:
        image: eclipse-mosquitto 
        volumes:
            - /home/$USER/broker/storage/mosquitto/config/:/mosquitto/config
            - /home/$USER/broker/storage/mosquitto/data/:/mosquitto/data
            - /home/$USER/broker/storage/mosquitto/log/:/mosquitto/log
        ports:
            - "8883:8883" 
            - "9001:9001"            
        networks:
          - my-mqtt
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
